# -*- coding: utf-8 -*-
"""Day6_Logistic_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j33zXPKAjLHp_mIVPVB984YWisBsAeTD
"""

import pandas as pd
import numpy as np

from google.colab import files
files.upload()
data = pd.read_csv('diabetes.csv')

data.head()

data.columns

data.shape

# extracting independent and dependent variable
feature_cols = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']
X = data[feature_cols] #Independent variable
y = data.Outcome # dependent variable

# split our dataset into training set and into testing set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.25,random_state=0)

# Model development and prediction

from sklearn.linear_model import LogisticRegression

# create Logistic Regression Classifier Object

logreg = LogisticRegression()

# fit the model with data

logreg.fit(x_train, y_train)

# prediction

y_pred = logreg.predict(x_test)
y_pred

# Evaluate the model using confusion matrix
# it is a matrix used to evaluate the performance of classification model
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, y_pred)
cnf_matrix

'''
                    predicted_no       predicted_yes

actual_no            TN = 115               FP = 15
actual_yes           FP =  25               TP = 37
'''

y_pred

y_test.values

print('Accuracy : ',metrics.accuracy_score(y_test,y_pred))